# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sign Application

on:
  push:
    tags:
      - '*'
  pull_request:
    tags:
      - '*'

jobs:
    
  build_and_sign:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: cheeckout repo
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: sign
      run: |
        npm ci
        npm run sign-firefox
      env:
        AMO_JWT_ISSUER: ${{secrets.MOZILLA_JWT_ISSUER}}
        AMO_JWT_SECRET: ${{secrets.MOZILLA_JWT_SECRET}}
    - name: archive result
      uses: actions/upload-artifact@v3
      with:
        name: addon-installer
        path: web-ext-artifacts/*.xpi
